In [1]:
import joblib
import pandas as pd
from sklearn.model_selection import GridSearchCV
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.preprocessing import MaxAbsScaler

In [3]:
def domain_age_lessThanOne(create_date, update_date):
    if create_date != "" and create_date != "expired" and not pd.isna(create_date):
        age = datetime.strptime("2024-04-23", '%Y-%m-%d') - datetime.strptime(create_date[:10],
                                                                              '%Y-%m-%d')
        return (age.days // 365) < 1

    elif create_date == "" and update_date != "":
        age = datetime.strptime("2024-04-23", '%Y-%m-%d') - datetime.strptime(update_date[:10],
                                                                              '%Y-%m-%d')
        if age.days < 365:
            return None
        else:
            return False

    elif create_date == "expired":
        return True

    return None

In [4]:
def binary_to_numeric(value):
    if value:
        return 1
    if not value:
        return 0
    else:
        return None

In [5]:
def preprocess_data(data, features):
    
    preprocessed_data = data[features].copy()
    preprocessed_data['new_domain'] = None
    for index, item in preprocessed_data.iterrows():
        new_domain = domain_age_lessThanOne(item['creation_date'], item['updated_date'])
        preprocessed_data.loc[index, 'new_domain'] = new_domain
        
    preprocessed_data = preprocessed_data.drop('creation_date', axis=1)
    preprocessed_data = preprocessed_data.drop('updated_date', axis=1)
        
    # Transform binary values to numerical
    preprocessed_data['control_over_dns'] = preprocessed_data['control_over_dns'].astype(float).replace({True: 1.0, False: 0.0})
    preprocessed_data['control_over_ssl'] = preprocessed_data['control_over_ssl'].astype(float).replace({True: 1.0, False: 0.0})
    preprocessed_data['domain_indexed'] = preprocessed_data['domain_indexed'].astype(float).replace({True: 1.0, False: 0.0})
    preprocessed_data['is_archived'] = preprocessed_data['is_archived'].astype(float).replace({True: 1.0, False: 0.0})
    preprocessed_data['known_hosting'] = preprocessed_data['known_hosting'].astype(float).replace({True: 1.0, False: 0.0})
    preprocessed_data['new_domain'] = preprocessed_data['new_domain'].astype(float).replace({True: 1.0, False: 0.0})
    preprocessed_data['is_on_root'] = preprocessed_data['is_on_root'].astype(float).replace({True: 1.0, False: 0.0})
    preprocessed_data['is_subdomain'] = preprocessed_data['is_subdomain'].astype(float).replace({True: 1.0, False: 0.0})
            
    return preprocessed_data

In [24]:
def train_imputers(X_train, numerical_features):
    features_with_missing = X_train.columns[X_train.isnull().any()].tolist()
    features_with_missing.sort(key=lambda x: X_train[x].isnull().sum())

    trained_imputers = {}
    best_params_dict = {}

    for feature in features_with_missing:
        complete_train = X_train.dropna(subset=[feature])
        
        param_grid = {
            "n_estimators": [100, 200, 500],
            "max_depth": [None, 5, 10],
            "min_samples_split": [2, 5, 10]
        }
        
        if feature in numerical_features:
            model = RandomForestRegressor(random_state=0)
            scoring = 'neg_mean_squared_error'
        else:
            model = RandomForestClassifier(random_state=0)
            scoring = 'accuracy'
        
        X_train_feat = complete_train.drop(feature, axis=1)
        y_train_feat = complete_train[feature]

        grid_search = GridSearchCV(model, param_grid, cv=5, scoring=scoring, n_jobs=-1)
        grid_search.fit(X_train_feat, y_train_feat)
        
        best_model = grid_search.best_estimator_
        best_params_dict[feature] = grid_search.best_params_
        
        # Store the trained imputer model for this feature
        trained_imputers[feature] = best_model

        # Impute missing values in the training set itself
        X_train_null = X_train[X_train[feature].isnull()].drop(feature, axis=1)
        if len(X_train_null) > 0:
            imputed_values = best_model.predict(X_train_null)
            X_train.loc[X_train[feature].isnull(), feature] = imputed_values
        
        # print(f"Feature: {feature}, Best Params: {grid_search.best_params_}, Best Score: {grid_search.best_score_}")

    # # Save the best parameters dictionary to a file for reference
    # joblib.dump(best_params_dict, path_prefix + 'best_params_dict_imputers.pkl')

    return X_train, trained_imputers


def apply_imputers(X_test, trained_imputers):
    for feature, imputer_model in trained_imputers.items():
        X_test_null = X_test[X_test[feature].isnull()].drop(feature, axis=1)
        if len(X_test_null) > 0:
            imputed_values = imputer_model.predict(X_test_null)
            X_test.loc[X_test[feature].isnull(), feature] = imputed_values
    return X_test


In [22]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

def perform_classification(data, labels, sample_ids):
    # Map labels to numeric values
    label_mapping = {'attackers_domain': 0, 'compromised_domain': 1, 'shared_domain': 2}
    y = labels.map(label_mapping)
    X = data.copy()
    
    numerical_features = ['between_archives_distance', 'phish_archives_distance']
    
    # Initialize list to collect max_abs_ values
    scaler_max_abs_list = []
    
    # Define hyperparameters for Random Forest Classifier
    param_grid = {
        'n_estimators': [100, 200, 500],
        'max_depth': [None, 5, 10, 20],
        'min_samples_split': [2, 5, 10],
        'class_weight': ['balanced', 'balanced_subsample']
    }
    model_to_tune = RandomForestClassifier(random_state=0)
    
    # Declare the inner and outer cross-validation strategies
    inner_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
    outer_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
    
    # Lists to collect results from each fold
    outer_confusion_matrices = []
    outer_precision_list = []
    outer_recall_list = []
    outer_f1_list = []
    y_true_list = []
    y_pred_list = []
    sample_id_list = []
    fold_data_list = []
    best_params_list = []
    
    for i, (outer_train_index, outer_test_index) in enumerate(outer_cv.split(X, y)):
        X_outer_train = X.iloc[outer_train_index].reset_index(drop=True)
        X_outer_test = X.iloc[outer_test_index].reset_index(drop=True)
        y_outer_train = y.iloc[outer_train_index].reset_index(drop=True)
        y_outer_test = y.iloc[outer_test_index].reset_index(drop=True)
        sample_ids_outer_test = sample_ids.iloc[outer_test_index].reset_index(drop=True)
    
        # Fit MaxAbsScaler on X_outer_train[numerical_features]
        scaler = MaxAbsScaler()
        scaler.fit(X_outer_train[numerical_features])

        # Collect max absolute values
        scaler_max_abs_list.append(scaler.max_abs_)

        # Transform numerical features
        X_outer_train_scaled = X_outer_train.copy()
        X_outer_test_scaled = X_outer_test.copy()
        X_outer_train_scaled[numerical_features] = scaler.transform(
            X_outer_train[numerical_features]
        )
        X_outer_test_scaled[numerical_features] = scaler.transform(
            X_outer_test[numerical_features]
        )
        
        # Handle missing values in training set and get trained imputers
        X_outer_train_scaled_imputed, trained_imputers = train_imputers(X_outer_train_scaled, numerical_features)

        # Apply trained imputers to test set
        X_outer_test_scaled_imputed = apply_imputers(X_outer_test_scaled, trained_imputers)

        # Inner cross-validation for parameter search on the current outer fold
        model = GridSearchCV(
            estimator=model_to_tune, param_grid=param_grid, cv=inner_cv, n_jobs=-1
        )
        model.fit(X_outer_train_scaled_imputed, y_outer_train)
    
        # Save best parameters from this fold
        best_params_list.append(model.best_params_)
    
        y_pred = model.predict(X_outer_test_scaled_imputed)
    
        confusion_matrix_values = confusion_matrix(y_outer_test, y_pred)
        outer_confusion_matrices.append(confusion_matrix_values)
    
        precision, recall, f1, _ = precision_recall_fscore_support(
            y_outer_test, y_pred, average=None, labels=[0, 1, 2]
        )
        outer_precision_list.append(precision)
        outer_recall_list.append(recall)
        outer_f1_list.append(f1)
    
        y_true_list.extend(y_outer_test)
        y_pred_list.extend(y_pred)
        sample_id_list.extend(sample_ids_outer_test)
    
        print(f"Outer Fold {i+1} Confusion Matrix:\n{outer_confusion_matrices[-1]}")
        # Print the precision, recall, and F1-score for each class
        for j, (p, r, f_val) in enumerate(zip(precision, recall, f1)):
            print(
                f"Outer Fold {i+1} Class {j} Precision: {p:.3f}, Recall: {r:.3f}, "
                f"F1-score: {f_val:.3f}"
            )
    
        # Save the predicted values and sample IDs for the current outer fold
        fold_data = X_outer_test.copy()
        fold_data['sample_id'] = sample_ids_outer_test
        fold_data['actual'] = y_outer_test.map({v: k for k, v in label_mapping.items()})
        fold_data['predicted'] = pd.Series(y_pred).map(
            {v: k for k, v in label_mapping.items()}
        )
        fold_data.to_csv(f"{path_prefix}random_forest_predictions_fold{i+1}.csv", index=False)
        fold_data_list.append(fold_data)
    
    # Save the predicted values for all folds
    fold_data_all = pd.concat(fold_data_list, axis=0).reset_index(drop=True)
    fold_data_all.to_csv(f"{path_prefix}random_forest_predictions_all.csv", index=False)
    
    # Aggregate best parameters from each fold
    best_params_df = pd.DataFrame(best_params_list)
    # Choose the parameters that appear most frequently
    best_params = best_params_df.mode().iloc[0].to_dict()
    
    # Ensure that hyperparameters have the correct data types
    param_types = {
        'n_estimators': int,
        'max_depth': lambda x: int(x) if not pd.isnull(x) else None,
        'min_samples_split': int,
        'criterion': str,
        'max_features': lambda x: x if x is None else str(x),
        'class_weight': lambda x: x if x is None else str(x)
    }
    
    for param, param_type in param_types.items():
        if param in best_params:
            best_params[param] = param_type(best_params[param])
    
   # Aggregate max absolute values from all folds
    scaler_max_abs_array = np.array(scaler_max_abs_list)
    aggregated_max_abs = np.mean(scaler_max_abs_array, axis=0)

    # Save the aggregated max absolute values
    max_abs_df = pd.DataFrame({
        'feature': numerical_features,
        'max_abs': aggregated_max_abs
    })
    max_abs_df.to_csv(f"{path_prefix}scaler_max_abs_values.csv", index=False)

    # Fit final scaler on entire dataset for future use
    final_scaler = MaxAbsScaler()
    final_scaler.fit(X[numerical_features])
    
    # Save the final scaler
    joblib.dump(final_scaler, f"{path_prefix}scaler.pkl")
    
    # Transform the entire dataset
    X_scaled = X.copy()
    X_scaled[numerical_features] = final_scaler.transform(X[numerical_features])
    
    # Retrain the final model on the entire dataset using the best hyperparameters
    model_final = RandomForestClassifier(**best_params, random_state=0)
    model_final.fit(X_scaled, y)
    
    # Save the final model
    joblib.dump(model_final, f"{path_prefix}random_forest_model.pkl")
    
    # Save the final model parameters
    model_params = model_final.get_params()
    with open(f"{path_prefix}random_forest_model_params.txt", 'w') as f:
        for param, value in model_params.items():
            f.write(f"{param}: {value}\n")
            
    # Retrain the final imputers
    X_scaled_imputed, trained_imputers = train_imputers(X_scaled, numerical_features)
    
    # After finalizing the imputation process and training imputers on the entire dataset:
    joblib.dump(trained_imputers, f"{path_prefix}trained_imputers.pkl")
    
    # Compute average precision, recall, and F1-score for each class across all folds
    average_precision = np.mean(outer_precision_list, axis=0)
    average_recall = np.mean(outer_recall_list, axis=0)
    average_f1 = np.mean(outer_f1_list, axis=0)
    
    # Print the average precision, recall, and F1-score for each class
    print("\nAverage Precision, Recall, and F1-score Across All Folds:")
    for j in range(len(average_precision)):
        print(
            f"Class {j} - Precision: {average_precision[j]:.3f}, "
            f"Recall: {average_recall[j]:.3f}, F1-score: {average_f1[j]:.3f}"
        )


In [8]:
# List of selected features
selected_features = [
    'creation_date',
    'updated_date',
    'control_over_ssl',
    'control_over_dns',
    'domain_indexed',
    'known_hosting',
    'is_archived',
    'is_on_root',
    'is_subdomain',
    'between_archives_distance',
    'phish_archives_distance'
]

In [9]:
numerical_features = ['between_archives_distance', 'phish_archives_distance']

In [12]:
# Load the data
path_prefix = '../data/'
df = pd.read_csv(path_prefix + 'validated_dataset_for_classification.csv')
target = df['verified_category']
ids = df['id']

In [13]:
# Preprocess the data
transformed_data = preprocess_data(df, selected_features)

In [14]:
import numpy as np
print(np.unique(target, return_counts=True))

(array(['attackers_domain', 'compromised_domain', 'shared_domain'],
      dtype=object), array([1376,  106, 3954]))


In [25]:
perform_classification(transformed_data, target, ids)

Outer Fold 1 Confusion Matrix:
[[270   5   1]
 [  2  18   2]
 [  3   3 784]]
Outer Fold 1 Class 0 Precision: 0.982, Recall: 0.978, F1-score: 0.980
Outer Fold 1 Class 1 Precision: 0.692, Recall: 0.818, F1-score: 0.750
Outer Fold 1 Class 2 Precision: 0.996, Recall: 0.992, F1-score: 0.994
Outer Fold 2 Confusion Matrix:
[[269   6   0]
 [  4  17   0]
 [  0   0 791]]
Outer Fold 2 Class 0 Precision: 0.985, Recall: 0.978, F1-score: 0.982
Outer Fold 2 Class 1 Precision: 0.739, Recall: 0.810, F1-score: 0.773
Outer Fold 2 Class 2 Precision: 1.000, Recall: 1.000, F1-score: 1.000
Outer Fold 3 Confusion Matrix:
[[274   1   0]
 [  3  16   2]
 [  5   1 785]]
Outer Fold 3 Class 0 Precision: 0.972, Recall: 0.996, F1-score: 0.984
Outer Fold 3 Class 1 Precision: 0.889, Recall: 0.762, F1-score: 0.821
Outer Fold 3 Class 2 Precision: 0.997, Recall: 0.992, F1-score: 0.995
Outer Fold 4 Confusion Matrix:
[[270   3   2]
 [  2  16   3]
 [  2   3 786]]
Outer Fold 4 Class 0 Precision: 0.985, Recall: 0.982, F1-score